// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1, arg2) {
  return window['go']['bindings']['Auth']['Login'](arg1, arg2);
}

export function MakeAuth(arg1) {
  return window['go']['bindings']['Auth']['MakeAuth'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['Auth']['Startup'](arg1);
}
