// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {entities} from '../models';
import {context} from '../models';

export function Login(arg1:string,arg2:string):Promise<models.LoginResult>;

export function MakeAuth(arg1:entities.User):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
