// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Startup(arg1:context.Context):Promise<void>;
